import { 
  Member, 
  Tier, 
  Transaction, 
  Tournament, 
  Sweepstakes, 
  SponsorPerk, 
  CharterFleet,
  VIPEvent,
  AnalyticsData
} from './types';

export const mockMember: Member = {
  id: 'm_1001',
  name: 'James Anderson',
  email: 'james@anderson-sports.com',
  role: 'Team Manager',
  organization: 'Anderson Sports Group',
  tier: 'Gold',
  lifetimeSpend: 2150000,
  ytdRebates: 84500,
  walletBalance: 12400,
  activeTrips: 3,
  totalBookings: 24,
  rebateRate: 4.5,
};

export const mockTiers: Tier[] = [
  { name: 'Bronze', threshold: 0, rebatePercentage: 1.5, perks: ['Standard Support', 'Virtual Card'] },
  { name: 'Silver', threshold: 500000, rebatePercentage: 2.5, perks: ['Priority Support', 'Lounge Access'] },
  { name: 'Gold', threshold: 1500000, rebatePercentage: 4.5, perks: ['Dedicated Concierge', 'Charter Upgrades'] },
  { name: 'Platinum', threshold: 3500000, rebatePercentage: 7.0, perks: ['Captain\'s Table Access', 'Private Aviation Priority'] },
];

export const mockTransactions: Transaction[] = [
  { id: 'tx_1', date: '2026-02-20', description: 'Costa Rica Pacific Expedition', amount: 32000, rebateEarned: 1440, status: 'Completed' },
  { id: 'tx_2', date: '2026-02-15', description: 'Private Jet Charter (MIA -> SJO)', amount: 45000, rebateEarned: 2025, status: 'Completed' },
  { id: 'tx_3', date: '2026-02-10', description: 'Yeti Gear Package', amount: 1200, rebateEarned: 54, status: 'Completed' },
  { id: 'tx_4', date: '2026-02-01', description: 'Bahamas Deep Sea Pursuit', amount: 48000, rebateEarned: 2160, status: 'Completed' },
  { id: 'tx_5', date: '2026-01-25', description: 'Marina VIP Lounge Access', amount: 800, rebateEarned: 36, status: 'Completed' },
];

export const mockTournaments: Tournament[] = [
  {
    id: 't_1',
    name: 'Offshore World Championship',
    city: 'Quepos',
    country: 'Costa Rica',
    region: 'Americas',
    lat: 9.4312,
    lng: -84.1618,
    startDate: '2026-04-19',
    endDate: '2026-04-23',
    status: 'Upcoming',
    species: ['Blue Marlin', 'Striped Marlin', 'Sailfish'],
    prizePool: '$500K+',
    entryFee: '$3,500 – $5,000',
    organizer: 'OWC / CatchStat',
    format: 'Teams bring own boats, weigh-ins at Marina Pez Vela',
    website: 'https://owc.catchstat.com',
    registrationDeadline: '2026-03-15',
  },
  {
    id: 't_2',
    name: 'Blue Marlin World Cup',
    city: 'Worldwide (HQ: Kailua-Kona)',
    country: 'USA / Global',
    region: 'Americas',
    lat: 19.6400,
    lng: -155.9969,
    startDate: '2026-07-04',
    endDate: '2026-07-04',
    status: 'Upcoming',
    species: ['Blue Marlin'],
    prizePool: '$1M+',
    entryFee: '$5,000',
    organizer: 'Blue Marlin World Cup LLC',
    format: 'Single-day event — teams fish anywhere in the world for 8 hours',
    website: 'https://bluemarlinworldcup.com',
    registrationDeadline: '2026-07-02',
  },
  {
    id: 't_3',
    name: 'Blue Marlin Grand Championship',
    city: 'Orange Beach',
    country: 'USA',
    region: 'Americas',
    lat: 30.2941,
    lng: -87.5733,
    startDate: '2026-07-15',
    endDate: '2026-07-19',
    status: 'Upcoming',
    species: ['Blue Marlin', 'White Marlin', 'Sailfish', 'Swordfish'],
    prizePool: '$1.8M',
    entryFee: '$5,000',
    organizer: 'BMGC',
    format: 'Weight and release divisions, Gulf of Mexico',
  },
  {
    id: 't_4',
    name: 'White Marlin Open',
    city: 'Ocean City',
    country: 'USA',
    region: 'Americas',
    lat: 38.3365,
    lng: -75.0849,
    startDate: '2026-08-03',
    endDate: '2026-08-07',
    status: 'Upcoming',
    species: ['White Marlin', 'Blue Marlin', 'Tuna', 'Wahoo', 'Dolphin'],
    prizePool: '$9M+',
    entryFee: '$1,400 – $1,700',
    organizer: 'White Marlin Open',
    format: 'Largest billfish tournament on the East Coast by purse',
    website: 'https://whitemarlinopen.com',
    registrationDeadline: '2026-06-01',
  },
  {
    id: 't_5',
    name: 'Bermuda Big Game Classic',
    city: 'Hamilton',
    country: 'Bermuda',
    region: 'Caribbean',
    lat: 32.3078,
    lng: -64.7505,
    startDate: '2026-07-08',
    endDate: '2026-07-10',
    status: 'Upcoming',
    species: ['Blue Marlin', 'White Marlin', 'Wahoo', 'Tuna'],
    prizePool: '$750K+',
    entryFee: '$5,000',
    organizer: 'Bermuda Triple Crown',
    format: '3-day billfish team event, up to 6 anglers per team',
    website: 'https://www.bermudabiggameclassic.com',
  },
  {
    id: 't_6',
    name: "Bisbee's Black & Blue",
    city: 'Cabo San Lucas',
    country: 'Mexico',
    region: 'Americas',
    lat: 22.8905,
    lng: -109.9167,
    startDate: '2026-10-20',
    endDate: '2026-10-24',
    status: 'Upcoming',
    species: ['Blue Marlin', 'Black Marlin', 'Striped Marlin'],
    prizePool: '$11.5M+',
    entryFee: '$5,000',
    organizer: "Bisbee's Fish & Wildlife Conservation Fund",
    format: '"Super Bowl of Fishing" — largest purse in sport fishing',
    website: 'https://bisbees.com',
  },
  {
    id: 't_7',
    name: 'Los Cabos Billfish Tournament',
    city: 'Cabo San Lucas',
    country: 'Mexico',
    region: 'Americas',
    lat: 22.9200,
    lng: -109.9100,
    startDate: '2026-10-10',
    endDate: '2026-10-14',
    status: 'Upcoming',
    species: ['Blue Marlin', 'Striped Marlin', 'Sailfish', 'Dorado'],
    prizePool: '$500K+',
    entryFee: '$5,000',
    organizer: 'Los Cabos Tournaments',
    format: 'Largest marlin, most releases, largest gamefish categories',
    website: 'https://www.loscabostournaments.com',
  },
  {
    id: 't_8',
    name: 'Kona Throw Down',
    city: 'Kailua-Kona',
    country: 'USA',
    region: 'Americas',
    lat: 19.6400,
    lng: -156.0000,
    startDate: '2026-07-06',
    endDate: '2026-07-09',
    status: 'Upcoming',
    species: ['Pacific Blue Marlin'],
    prizePool: 'Winner-takes-all',
    entryFee: '$5,150',
    organizer: 'Kona Throw Down LLC',
    format: 'Winner-takes-all for largest marlin, optional jackpots',
  },
  {
    id: 't_9',
    name: 'IGFA Red Sea Championship',
    city: 'El Gouna',
    country: 'Egypt',
    region: 'Middle East',
    lat: 27.1828,
    lng: 33.8599,
    startDate: '2026-02-11',
    endDate: '2026-02-14',
    status: 'Active',
    species: ['Giant Trevally', 'Barracuda', 'Grouper', 'Sailfish'],
    prizePool: '$100K+',
    entryFee: '$4,000',
    organizer: 'IGFA',
    format: '3 days of fishing from Abu Tig Marina, Red Sea fishery',
    website: 'https://igfa.org/tournaments',
  },
  {
    id: 't_10',
    name: 'IGFA Open',
    city: 'Quepos',
    country: 'Costa Rica',
    region: 'Americas',
    lat: 9.4300,
    lng: -84.1650,
    startDate: '2026-03-12',
    endDate: '2026-03-14',
    status: 'Upcoming',
    species: ['Blue Marlin', 'Black Marlin', 'Sailfish', 'Tuna', 'Dorado'],
    prizePool: '$250K+',
    entryFee: '$5,000',
    organizer: 'IGFA',
    format: 'Billfish release format — points for marlin & sailfish releases',
    website: 'https://igfa.org/tournaments',
  },
  {
    id: 't_11',
    name: 'IGFA Walker\'s Cay Shootout',
    city: 'Walker\'s Cay',
    country: 'Bahamas',
    region: 'Caribbean',
    lat: 27.2614,
    lng: -78.3989,
    startDate: '2026-04-22',
    endDate: '2026-04-25',
    status: 'Upcoming',
    species: ['Blue Marlin', 'White Marlin', 'Sailfish'],
    prizePool: '$200K+',
    entryFee: '$4,500',
    organizer: 'IGFA',
    format: 'Release tournament in the northern Bahamas out-islands',
    website: 'https://igfa.org/tournaments',
  },
  {
    id: 't_12',
    name: 'GoFish Nagambie',
    city: 'Nagambie',
    country: 'Australia',
    region: 'Asia-Pacific',
    lat: -36.7833,
    lng: 145.1500,
    startDate: '2026-03-20',
    endDate: '2026-03-22',
    status: 'Upcoming',
    species: ['Murray Cod', 'Golden Perch', 'Trout'],
    prizePool: '$80,000',
    entryFee: '$160 (Adult) / $95 (Junior)',
    organizer: 'GoFish Tournament',
    format: 'Open to boats, kayaks, and shore — junior and female categories',
    website: 'https://gofishtournament.com.au',
  },
  {
    id: 't_13',
    name: 'NZ International Billfish Tournament',
    city: 'Bay of Islands',
    country: 'New Zealand',
    region: 'Asia-Pacific',
    lat: -35.2282,
    lng: 174.0908,
    startDate: '2026-03-04',
    endDate: '2026-03-08',
    status: 'Upcoming',
    species: ['Striped Marlin', 'Blue Marlin', 'Yellowfin Tuna', 'Mahi Mahi'],
    prizePool: 'NZ$300K+',
    entryFee: 'NZ$3,500',
    organizer: 'NZ Billfish Association',
    format: 'Tag & release with weigh-in options, Bay of Islands waters',
  },
  {
    id: 't_14',
    name: 'Cabo Triple Crown',
    city: 'Cabo San Lucas',
    country: 'Mexico',
    region: 'Americas',
    lat: 22.8800,
    lng: -109.9300,
    startDate: '2026-09-15',
    endDate: '2026-11-01',
    status: 'Upcoming',
    species: ['Marlin', 'Tuna', 'Dorado', 'Wahoo'],
    prizePool: '$3M+',
    entryFee: '$3,000',
    organizer: 'Pelagic Tournaments',
    format: 'Three-tournament series across Cabo (Sep–Nov)',
    website: 'https://pelagictournaments.com',
  },
  {
    id: 't_15',
    name: 'Seychelles International Fishing Tournament',
    city: 'Victoria (Mahé)',
    country: 'Seychelles',
    region: 'Africa',
    lat: -4.6191,
    lng: 55.4513,
    startDate: '2026-03-25',
    endDate: '2026-03-29',
    status: 'Upcoming',
    species: ['Sailfish', 'Yellowfin Tuna', 'Dogtooth Tuna', 'Giant Trevally'],
    prizePool: '$150K+',
    entryFee: '$2,500',
    organizer: 'Seychelles Sport Fishing Club',
    format: 'Offshore & inshore divisions, Indian Ocean game fishing',
  },
  {
    id: 't_16',
    name: 'Mediterranean IGFA Championship',
    city: 'Valencia',
    country: 'Spain',
    region: 'Europe',
    lat: 39.4699,
    lng: -0.3763,
    startDate: '2026-06-10',
    endDate: '2026-06-14',
    status: 'Upcoming',
    species: ['Bluefin Tuna', 'Albacore', 'Swordfish'],
    prizePool: '€200K',
    entryFee: '€3,500',
    organizer: 'IGFA / Mediterranean Fishing Federation',
    format: 'Offshore Mediterranean big-game, catch & release emphasis',
    website: 'https://igfa.org/tournaments',
  },
  {
    id: 't_17',
    name: 'NPFL Stop Two — Wright Patman Lake',
    city: 'Texarkana',
    country: 'USA',
    region: 'Americas',
    lat: 33.4418,
    lng: -94.0477,
    startDate: '2026-04-23',
    endDate: '2026-04-25',
    status: 'Upcoming',
    species: ['Largemouth Bass'],
    prizePool: '$100K+',
    entryFee: 'Free (qualified)',
    organizer: 'National Professional Fishing League',
    format: 'No-entry-fee qualifying stop, professional bass circuit',
    website: 'https://thenationalprofessionalfishingleague.com',
  },
  {
    id: 't_18',
    name: 'IGFA Permit Invitational',
    city: 'Key West',
    country: 'USA',
    region: 'Americas',
    lat: 24.5551,
    lng: -81.7800,
    startDate: '2026-09-30',
    endDate: '2026-10-03',
    status: 'Upcoming',
    species: ['Permit'],
    prizePool: '$50K+',
    entryFee: '$3,000',
    organizer: 'IGFA',
    format: 'Fly & light-tackle permit tournament, Florida Keys flats',
    website: 'https://igfa.org/tournaments',
  },
];

export const mockSweepstakes: Sweepstakes[] = [
  { id: 's_1', title: 'Ultimate Bahamas Getaway', prize: 'All-inclusive 5-day trip for 2 on a private yacht', value: '$25,000', deadline: '2026-03-31', totalEntries: 14500, myEntries: 15, image: 'https://images.unsplash.com/photo-1507525428034-b723cf961d3e?auto=format&fit=crop&w=800&q=80' },
  { id: 's_2', title: 'Pro Gear Upgrade', prize: 'Custom Shimano & Yeti offshore package', value: '$8,500', deadline: '2026-03-15', totalEntries: 8200, myEntries: 5, image: 'https://images.unsplash.com/photo-1514282401047-d79a71a590e8?auto=format&fit=crop&w=800&q=80' },
];

export const mockSponsorPerks: SponsorPerk[] = [
  { id: 'sp_1', sponsor: 'Yeti', title: 'Complimentary Cooler Package', description: 'Get a free Tundra 45 with any 7+ day booking.' },
  { id: 'sp_2', sponsor: 'Costa', title: 'VIP Lounge Access', description: 'Free entry to the Costa Marina Lounge at all major tournaments.' },
  { id: 'sp_3', sponsor: 'Shimano', title: 'Gear Rental Upgrade', description: 'Complimentary upgrade to Stella Tiagra setups on all charters.' },
];

export const mockCharterFleet: CharterFleet[] = [
  { id: 'c_1', name: 'Gulfstream G650', type: 'Jet', capacity: 14, range: '7,000 nm', amenities: ['Wi-Fi', 'Full Galley', 'Lie-flat beds'], image: 'https://images.unsplash.com/photo-1559080463-5c7eb3a52de1?auto=format&fit=crop&w=800&q=80' },
  { id: 'c_2', name: 'Citation Challenger', type: 'Jet', capacity: 9, range: '4,000 nm', amenities: ['Wi-Fi', 'Refreshment Center'], image: 'https://images.unsplash.com/photo-1540962351504-03099e0a754b?auto=format&fit=crop&w=800&q=80' },
  { id: 'c_3', name: 'Viking 72 Convertible', type: 'Sportfisher', capacity: 8, range: '400 nm', amenities: ['Seakeeper', 'Mezzanine A/C', 'Tournament Rigged'], image: 'https://images.unsplash.com/photo-1569263979104-865ab7cd8d13?auto=format&fit=crop&w=800&q=80' },
];

export const mockCaptainsTableEvents: VIPEvent[] = [
  { id: 'v_1', title: 'Private Dinner with Billfish Champions', date: '2026-03-14', location: 'Quepos, Costa Rica', capacity: 12, spotsRemaining: 3, image: 'https://images.unsplash.com/photo-1414235077428-338989a2e8c0?auto=format&fit=crop&w=800&q=80' },
  { id: 'v_2', title: 'Sponsor Mixer & Gear Preview', date: '2026-04-09', location: 'Cabo San Lucas, Mexico', capacity: 50, spotsRemaining: 15, image: 'https://images.unsplash.com/photo-1511795409834-ef04bbd61622?auto=format&fit=crop&w=800&q=80' },
];

export const mockAnalytics: AnalyticsData = {
  monthlyRevenue: [
    { month: 'Jan', revenue: 250000 },
    { month: 'Feb', revenue: 380000 },
    { month: 'Mar', revenue: 420000 },
    { month: 'Apr', revenue: 510000 },
    { month: 'May', revenue: 680000 },
    { month: 'Jun', revenue: 850000 },
  ],
  topDestinations: [
    { name: 'Costa Rica', bookings: 145 },
    { name: 'Bahamas', bookings: 112 },
    { name: 'Mexico', bookings: 89 },
    { name: 'Panama', bookings: 64 },
  ],
  rebateDistribution: [
    { name: 'Bronze', value: 15 },
    { name: 'Silver', value: 25 },
    { name: 'Gold', value: 40 },
    { name: 'Platinum', value: 20 },
  ],
  memberGrowth: [
    { month: 'Jan', members: 120 },
    { month: 'Feb', members: 180 },
    { month: 'Mar', members: 250 },
    { month: 'Apr', members: 340 },
    { month: 'May', members: 480 },
    { month: 'Jun', members: 650 },
  ],
  sponsors: [
    { name: 'Yeti', activations: 450, revenue: 125000, roi: '340%' },
    { name: 'Costa', activations: 380, revenue: 98000, roi: '280%' },
    { name: 'Shimano', activations: 290, revenue: 145000, roi: '410%' },
  ]
};
